import { AutomobileLang, AutomobileTemplateBank } from "./automobileTypes";

export const AUTOMOBILE_BRAND_NAME = "Apex Motors";

export const AUTOMOBILE_TEMPLATES: Record<AutomobileLang, AutomobileTemplateBank> = {
  "en-IN": {
    greeting: `Hello and welcome to ${AUTOMOBILE_BRAND_NAME}! I'm your virtual auto assistant. I can help you with new car inquiries, test drives, service bookings, or vehicle support. How may I assist you today?`,
    askName: "May I have your full name please?",
    askMobile: "Thank you, {name}! Could you please share your 10-digit mobile number?",
    askVehicle: "Which car model are you interested in — for example Creta, Nexon, Brezza, XUV700, or an EV?",
    askRegNumber: "Sure, {name}! Could you please share your vehicle registration number (e.g. UP16AB1234)?",
    askServiceType: "What type of service does your {vehicle} need — periodic maintenance, AC/brake inspection, or a specific repair?",
    askDealer: "Which dealership location is most convenient for you — Gurgaon, Noida, or South Delhi?",
    askSlot: "When would you prefer to schedule this? Our workshops are open Monday to Saturday, 9:00 AM to 6:30 PM.",
    askTime: "Got it for {date}. What time would suit you best? Slots are available between 9:30 AM and 5:00 PM.",
    askPurchaseTimeline: "Great choice! When are you planning to purchase or take delivery — within this month, or in the coming months?",
    outOfHours: "I'm sorry, our service centers operate Monday to Saturday, 9:00 AM to 6:30 PM, and remain closed on Sundays. Could you choose a time within those hours?",
    serviceConfirmation: "Let me confirm your service booking: {name}, mobile {mobile}, for your {vehicle} ({regNo}) at our {dealer} center on {slot}. Is that correct?",
    testDriveConfirmation: "Let me confirm your test drive: {name}, mobile {mobile}, for the {vehicle} at {dealer} on {slot}. Shall I book this for you?",
    salesLeadConfirmation: "Thank you {name}! I have noted your interest in the {vehicle} at {dealer}. Our sales specialist will call you on {mobile} shortly.",
    bookingConfirmed: "Your appointment is confirmed! Booking details have been sent to your WhatsApp. Your reference ID is {id}.",
    roadsideAssistanceAlert: "This sounds like an urgent vehicle emergency. Please park safely with hazard lights on. Our 24/7 Roadside Assistance helpline is 1800-102-9999. Emergency dispatch ticket #{id} has been initiated.",
    jobCardStatusFound: "Status for {regNo}: Job Card #{jobCard}. Current stage: {stage}. Estimated ready time: {estTime}. Advisor: {advisor} ({contact}).",
    serviceEstimateProvided: "Estimated cost for {vehicle} ({serviceType}) is {estimate}. Includes: {includes}.",
    humanHandoff: "I'm connecting you with our dedicated customer support specialist right now. Please stay on the line.",
    couldNotUnderstand: "I'm sorry, I didn't quite catch that. Could you please repeat?",
    farewell: `Thank you for choosing ${AUTOMOBILE_BRAND_NAME}. Have a safe journey and a wonderful day ahead!`,
    alreadyConfirmed: "Your appointment is already confirmed under reference ID {id}. Is there anything else I can help you with?",
  },
  "hi-IN": {
    greeting: `नमस्ते! ${AUTOMOBILE_BRAND_NAME} में आपका स्वागत है। मैं आपका वर्चुअल ऑटो असिस्टेंट हूँ। नई कार, टेस्ट ड्राइव, सर्विस बुकिंग या सहायता में आपकी मदद कर सकता हूँ। आज मैं आपकी क्या मदद करूँ?`,
    askName: "कृपया अपना पूरा नाम बताइए?",
    askMobile: "धन्यवाद, {name} जी! कृपया अपना 10 अंकों का मोबाइल नंबर बताइए?",
    askVehicle: "आप किस कार मॉडल में रुचि रखते हैं — जैसे Creta, Nexon, Brezza, XUV700 या कोई EV?",
    askRegNumber: "ज़रूर {name} जी! कृपया अपनी गाड़ी का रजिस्ट्रेशन नंबर (जैसे UP16AB1234) बताइए?",
    askServiceType: "आपकी {vehicle} को किस तरह की सर्विस चाहिए — रेगुलर सर्विस, एसी/ब्रेक चेकअप, या कोई खास खराबी?",
    askDealer: "आपके लिए कौन सा शोरूम या सर्विस सेंटर सुविधाजनक रहेगा — गुड़गांव, नोएडा या साउथ दिल्ली?",
    askSlot: "आप किस दिन आना चाहेंगे? हमारे सर्विस सेंटर सोमवार से शनिवार सुबह 9:00 से शाम 6:30 बजे तक खुले हैं।",
    askTime: "{date} नोट कर लिया है। आप किस समय आना चाहेंगे? सुबह 9:30 से शाम 5:00 बजे के बीच समय उपलब्ध है।",
    askPurchaseTimeline: "बहुत बढ़िया पसंद! आप गाड़ी कब तक खरीदने की योजना बना रहे हैं — इसी महीने या अगले महीने?",
    outOfHours: "माफ़ कीजिए, हमारे सर्विस सेंटर सिर्फ सोमवार से शनिवार सुबह 9:00 से शाम 6:30 बजे तक खुले हैं, रविवार बंद। क्या इन घंटों में कोई समय ठीक रहेगा?",
    serviceConfirmation: "तो कन्फर्म कर दूँ: {name}, मोबाइल {mobile}, {vehicle} ({regNo}) के लिए {dealer} सेंटर पर {slot} को। क्या यह सही है?",
    testDriveConfirmation: "तो कन्फर्म कर दूँ: {name}, मोबाइल {mobile}, {vehicle} की टेस्ट ड्राइव {dealer} पर {slot} को। क्या मैं इसे बुक कर दूँ?",
    salesLeadConfirmation: "धन्यवाद {name} जी! {vehicle} के लिए आपकी जानकारी नोट कर ली गई है। हमारे सेल्स एक्सपर्ट आपसे {mobile} पर संपर्क करेंगे।",
    bookingConfirmed: "आपकी बुकिंग कन्फर्म हो गई है! विवरण आपके व्हाट्सऐप पर भेज दिया गया है। आपकी रेफरेंस आईडी है {id}।",
    roadsideAssistanceAlert: "यह इमरजेंसी ब्रेकडाउन लग रहा है। कृपया गाड़ी को साइड में पार्क करें। हमारी 24/7 हेल्पलाइन है 1800-102-9999। इमरजेंसी टिकट #{id} दर्ज कर लिया गया है।",
    jobCardStatusFound: "{regNo} का स्टेटस: जॉब कार्ड #{jobCard}। वर्तमान स्टेज: {stage}। तैयार होने का समय: {estTime}। एडवाइजर: {advisor} ({contact})।",
    serviceEstimateProvided: "{vehicle} ({serviceType}) का अनुमानित खर्च {estimate} है। इसमें शामिल है: {includes}।",
    humanHandoff: "मैं आपकी कॉल तुरंत हमारे कस्टमर सपोर्ट स्पेशलिस्ट को ट्रांसफर कर रहा हूँ। कृपया लाइन पर बने रहें।",
    couldNotUnderstand: "माफ़ कीजिए, मैं समझ नहीं पाया। क्या आप फिर से बता सकते हैं?",
    farewell: `${AUTOMOBILE_BRAND_NAME} को चुनने के लिए धन्यवाद। सुरक्षित ड्राइव करें और आपका दिन शुभ हो!`,
    alreadyConfirmed: "आपकी बुकिंग पहले ही रेफरेंस आईडी {id} के तहत कन्फर्म हो चुकी है। क्या मैं आपकी किसी और चीज़ में मदद करूँ?",
  },
  "ta-IN": {
    greeting: `வணக்கம்! ${AUTOMOBILE_BRAND_NAME}-க்கு நல்வரவு. புதிய கார்கள், டெஸ்ட் டிரைவ், அல்லது சர்வீஸ் புக்கிங்கில் உதவ முடியும். இன்று எப்படி உதவலாம்?`,
    askName: "உங்கள் முழுப் பெயரைச் சொல்ல முடியுமா?",
    askMobile: "நன்றி, {name}! உங்கள் 10 இலக்க மொபைல் எண்ணைத் தெரிவிக்க முடியுமா?",
    askVehicle: "நீங்கள் எந்த காரில் ஆர்வமாக உள்ளீர்கள் — Creta, Nexon, Brezza, அல்லது EV?",
    askRegNumber: "உங்கள் வாகன பதிவு எண்ணைத் (எ.கா. UP16AB1234) தெரிவிக்க முடியுமா?",
    askServiceType: "உங்கள் {vehicle}-க்கு என்ன சர்வீஸ் தேவை — பீரியாடிக் சர்வீஸ் அல்லது ஏதேனும் பழுதா?",
    askDealer: "குர்கான், நொய்டா, அல்லது தென் டெல்லி — இதில் எந்த இடம் உங்களுக்கு வசதியானது?",
    askSlot: "திங்கள் முதல் சனி வரை காலை 9:00 முதல் மாலை 6:30 வரை திறந்திருக்கிறோம். எப்போது வர விரும்புகிறீர்கள்?",
    askTime: "{date} குறித்தாயிற்று. எந்த நேரத்தில் வர விரும்புகிறீர்கள்?",
    askPurchaseTimeline: "எப்போது காரை வாங்க திட்டமிட்டுள்ளீர்கள்?",
    outOfHours: "மன்னிக்கவும், ஞாயிற்றுக்கிழமை விடுமுறை. வேலை நாட்களில் ஒரு நேரத்தைத் தேர்ந்தெடுக்கவும்.",
    serviceConfirmation: "உறுதி செய்கிறேன்: {name}, மொபைல் {mobile}, {vehicle} ({regNo}), {dealer} மையத்தில் {slot} அன்று. இது சரியா?",
    testDriveConfirmation: "உறுதி செய்கிறேன்: {name}, {vehicle} டெஸ்ட் டிரைவ் {dealer}-ல் {slot} அன்று. பதிவு செய்யவா?",
    salesLeadConfirmation: "நன்றி {name}! எங்கள் விற்பனை ஆலோசகர் உங்களை {mobile}-ல் விரைவில் தொடர்பு கொள்வார்.",
    bookingConfirmed: "உங்கள் அப்பாயிண்ட்மென்ட் உறுதி செய்யப்பட்டது! ரெஃபரன்ஸ் ஐடி {id}. விவரங்கள் வாட்ஸ்அப்பில் அனுப்பப்பட்டுள்ளன.",
    roadsideAssistanceAlert: "அவசர சாலை உதவிக்கு 1800-102-9999 அழைக்கவும். அவசர கோரிக்கை #{id} பதிவு செய்யப்பட்டுள்ளது.",
    jobCardStatusFound: "{regNo} நிலை: ஜாப் கார்டு #{jobCard}, நிலை: {stage}, நேரம்: {estTime}.",
    serviceEstimateProvided: "{vehicle} ({serviceType}) உத்தேச செலவு: {estimate}.",
    humanHandoff: "எங்கள் வாடிக்கையாளர் சேவை அதிகாரியுடன் இணைக்கிறேன், காத்திருக்கவும்.",
    couldNotUnderstand: "மன்னிக்கவும், புரியவில்லை. மீண்டும் சொல்ல முடியுமா?",
    farewell: `${AUTOMOBILE_BRAND_NAME}-ஐ அழைத்ததற்கு நன்றி. பாதுகாப்பாக ஓட்டுங்கள், நல்ல நாளாக அமையட்டும்!`,
    alreadyConfirmed: "உங்கள் பதிவு ஏற்கனவே உறுதி செய்யப்பட்டுள்ளது — ரெஃபரன்ஸ் ஐடி {id}.",
  },
  "te-IN": {
    greeting: `నమస్కారం! ${AUTOMOBILE_BRAND_NAME} కి స్వాగతం. కొత్త కార్లు, టెస్ట్ డ్రైవ్ మరియు సర్వీస్ బుకింగ్‌లో సహాయపడగలను. మీకు ఎలా సహాయపడగలను?`,
    askName: "మీ పూర్తి పేరు చెప్పగలరా?",
    askMobile: "ధన్యవాదాలు {name}! మీ 10 అంకెల మొబైల్ నంబర్ చెప్పగలరా?",
    askVehicle: "మీరు ఏ కారు మోడల్‌పై ఆసక్తి చూపిస్తున్నారు — Creta, Nexon, Brezza, లేదా EV?",
    askRegNumber: "మీ వాహనం రిజిస్ట్రేషన్ నంబర్ (ఉదా: UP16AB1234) చెప్పగలరా?",
    askServiceType: "మీ {vehicle} కి ఎలాంటి సర్వీస్ కావాలి — రెగ్యులర్ సర్వీస్ లేదా ఏదైనా రిపేరా?",
    askDealer: "గుర్‌గావ్, నోయిడా, లేదా సౌత్ ఢిల్లీ — ఏ సెంటర్ మీకు సౌకర్యవంతంగా ఉంటుంది?",
    askSlot: "సోమవారం నుండి శనివారం వరకు ఉదయం 9:00 నుండి సాయంత్రం 6:30 వరకు తెరిచి ఉంటాము. ఎప్పుడు రాగలరు?",
    askTime: "{date} నోట్ చేసుకున్నాను. ఏ సమయానికి రాగలరు?",
    askPurchaseTimeline: "ఎప్పటిలోగా కారు కొనాలని ప్లాన్ చేస్తున్నారు?",
    outOfHours: "క్షమించండి, ఆదివారం సెలవు. దయచేసి పనివేళల్లో సమయాన్ని ఎంచుకోండి.",
    serviceConfirmation: "నిర్ధారిస్తున్నాను: {name}, మొబైల్ {mobile}, {vehicle} ({regNo}), {dealer} వద్ద {slot} న. ఇది సరైనదేనా?",
    testDriveConfirmation: "నిర్ధారిస్తున్నాను: {name}, {vehicle} టెస్ట్ డ్రైవ్ {dealer} వద్ద {slot} న. బుక్ చేయమంటారా?",
    salesLeadConfirmation: "ధన్యవాదాలు {name}! మా సేల్స్ టీమ్ మిమ్మల్ని {mobile} లో సంప్రదిస్తుంది.",
    bookingConfirmed: "మీ అపాయింట్‌మెంట్ నిర్ధారించబడింది! రిఫరెన్స్ ఐడి {id}. వివరాలు వాట్సాప్‌కి పంపబడ్డాయి.",
    roadsideAssistanceAlert: "రోడ్‌సైడ్ అసిస్టెన్స్ కోసం 1800-102-9999 కి కాల్ చేయండి. ఎమర్జెన్సీ టికెట్ #{id} నమోదైంది.",
    jobCardStatusFound: "{regNo} స్థితి: జాబ్ కార్డ్ #{jobCard}, ప్రస్తుత దశ: {stage}, అంచనా సమయం: {estTime}.",
    serviceEstimateProvided: "{vehicle} ({serviceType}) అంచనా ఖర్చు: {estimate}.",
    humanHandoff: "మా సర్వీస్ ఎగ్జిక్యూటివ్‌తో కనెక్ట్ చేస్తున్నాను, లైన్‌లో ఉండండి.",
    couldNotUnderstand: "క్షమించండి, అర్థం కాలేదు. మళ్ళీ చెప్పగలరా?",
    farewell: `${AUTOMOBILE_BRAND_NAME} కి కాల్ చేసినందుకు ధన్యవాదాలు. సేఫ్ డ్రైవ్ చేయండి!`,
    alreadyConfirmed: "మీ అపాయింట్‌మెంట్ ఇప్పటికే నిర్ధారించబడింది — రిఫరెన్స్ ఐడి {id}.",
  },
  "bn-IN": {
    greeting: `নমস্কার! ${AUTOMOBILE_BRAND_NAME}-এ আপনাকে স্বাগতম। নতুন গাড়ি, টেস্ট ড্রাইভ বা সার্ভিস বুকিংয়ে আমি সাহায্য করতে পারি। আজ কীভাবে সাহায্য করতে পারি?`,
    askName: "আপনার পুরো নাম বলবেন কি?",
    askMobile: "ধন্যবাদ {name}! আপনার ১০ সংখ্যার মোবাইল নম্বরটি বলবেন?",
    askVehicle: "আপনি কোন গাড়ির মডেলে আগ্রহী — যেমন Creta, Nexon, Brezza, বা EV?",
    askRegNumber: "আপনার গাড়ির রেজিস্ট্রেশন নম্বর (যেমন UP16AB1234) বলবেন কি?",
    askServiceType: "আপনার {vehicle}-এর কী ধরনের সার্ভিস প্রয়োজন — রেগুলার সার্ভিস নাকি কোনো সমস্যা হচ্ছে?",
    askDealer: "গুরগাঁও, নয়ডা, নাকি দক্ষিণ দিল্লি — কোন শাখা আপনার জন্য সুবিধাজনক?",
    askSlot: "সোমবার থেকে শনিবার সকাল ৯:০০ থেকে সন্ধ্যা ৬:৩০ পর্যন্ত খোলা থাকে। কবে আসতে চান?",
    askTime: "{date} লিখে নিয়েছি। কোন সময়ে আসতে সুবিধা হবে?",
    askPurchaseTimeline: "কবে গাড়ি কেনার পরিকল্পনা করছেন?",
    outOfHours: "দুঃখিত, রবিবার বন্ধ থাকে। অনুগ্রহ করে কাজের দিনের মধ্যে একটি সময় বেছে নিন।",
    serviceConfirmation: "তাহলে নিশ্চিত করছি: {name}, মোবাইল {mobile}, {vehicle} ({regNo}), {dealer} শাখায় {slot}-এ। এটা কি ঠিক আছে?",
    testDriveConfirmation: "নিশ্চিত করছি: {name}, {vehicle} টেস্ট ড্রাইভ {dealer} শাখায় {slot}-এ। বুক করে দেব?",
    salesLeadConfirmation: "ধন্যবাদ {name}! আমাদের সেলস বিশেষজ্ঞ শীঘ্রই {mobile} নম্বরে আপনার সাথে যোগাযোগ করবেন।",
    bookingConfirmed: "আপনার বুকিং নিশ্চিত হয়ে গেছে! রেফারেন্স আইডি {id}। বিস্তারিত হোয়াটসঅ্যাপে পাঠানো হয়েছে।",
    roadsideAssistanceAlert: "জরুরী রোডসাইড সহায়তার জন্য 1800-102-9999 নম্বরে কল করুন। অনুরোধ #{id} নথিভুক্ত হয়েছে।",
    jobCardStatusFound: "{regNo} স্ট্যাটাস: জব কার্ড #{jobCard}, বর্তমান পর্যায়: {stage}, সম্ভাব্য সময়: {estTime}।",
    serviceEstimateProvided: "{vehicle} ({serviceType}) সম্ভাব্য খরচ: {estimate}।",
    humanHandoff: "আমাদের কাস্টমার কেয়ার প্রতিনিধির সাথে কথা বলিয়ে দিচ্ছি, লাইনে থাকুন।",
    couldNotUnderstand: "দুঃখিত, বুঝতে পারিনি। আবার বলবেন কি?",
    farewell: `${AUTOMOBILE_BRAND_NAME}-এ কল করার জন্য ধন্যবাদ। সাবধানে গাড়ি চালান, দিনটি শুভ হোক!`,
    alreadyConfirmed: "আপনার অ্যাপয়েন্টমেন্ট ইতিমধ্যে নিশ্চিত রয়েছে — রেফারেন্স আইডি {id}।",
  },
  "ml-IN": {
    greeting: `നമസ്കാരം! ${AUTOMOBILE_BRAND_NAME}-ലേക്ക് സ്വാഗതം. പുതിയ കാറുകൾ, ടെസ്റ്റ് ഡ്രൈവ്, സർവീസ് ബുക്കിംഗ് എന്നിവയ്ക്ക് സഹായിക്കാം. എങ്ങനെ സഹായിക്കണം?`,
    askName: "നിങ്ങളുടെ മുഴുവൻ പേര് പറയാമോ?",
    askMobile: "നന്ദി {name}! നിങ്ങളുടെ 10 അക്ക മൊബൈൽ നമ്പർ പങ്കുവെക്കാമോ?",
    askVehicle: "ഏത് കാർ മോഡലിലാണ് താത്പര്യം — Creta, Nexon, Brezza അതോ EV?",
    askRegNumber: "വാഹനത്തിന്റെ രജിസ്ട്രേഷൻ നമ്പർ (ഉദാ: UP16AB1234) പറയാമോ?",
    askServiceType: "{vehicle}-ന് ഏത് തരത്തിലുള്ള സർവീസാണ് വേണ്ടത് — പീരിയോഡിക് സർവീസ് അതോ റിപ്പയറോ?",
    askDealer: "ഗുഡ്ഗാവ്, നോയിഡ, സൗത്ത് ഡൽഹി — ഇതിൽ ഏതാണ് സൗകര്യപ്രദം?",
    askSlot: "തിങ്കൾ മുതൽ ശനി വരെ രാവിലെ 9:00 മുതൽ വൈകുന്നേരം 6:30 വരെ വർക്ക്‌ഷോപ്പുകൾ പ്രവർത്തിക്കുന്നു. എപ്പോഴാണ് വരാൻ ഉദ്ദേശിക്കുന്നത്?",
    askTime: "{date} നോട്ട് ചെയ്തിട്ടുണ്ട്. ഏത് സമയമാണ് സൗകര്യം?",
    askPurchaseTimeline: "എപ്പോഴാണ് കാർ വാങ്ങാൻ ഉദ്ദേശിക്കുന്നത്?",
    outOfHours: "ക്ഷമിക്കണം, ഞായറാഴ്ച അവധിയാണ്. പ്രവൃത്തി സമയത്ത് ഒരു സമയം തിരഞ്ഞെടുക്കുക.",
    serviceConfirmation: "ഉറപ്പാക്കുന്നു: {name}, മൊബൈൽ {mobile}, {vehicle} ({regNo}), {dealer} സെന്ററിൽ {slot}-ന്. ഇത് ശരിയാണോ?",
    testDriveConfirmation: "ഉറപ്പാക്കുന്നു: {name}, {vehicle} ടെസ്റ്റ് ഡ്രൈവ് {dealer}-ൽ {slot}-ന്. ബുക്ക് ചെയ്യട്ടെ?",
    salesLeadConfirmation: "നന്ദി {name}! ഞങ്ങളുടെ സെയിൽസ് ടീം {mobile}-ൽ ബന്ധപ്പെടും.",
    bookingConfirmed: "ബുക്കിംഗ് സ്ഥിരീകരിച്ചു! റഫറൻസ് ഐഡി {id}. വിവരങ്ങൾ വാട്സാപ്പിൽ അയച്ചിട്ടുണ്ട്.",
    roadsideAssistanceAlert: "അടിയന്തിര റോഡ് സഹായത്തിന് 1800-102-9999 എന്ന നമ്പറിൽ വിളിക്കുക. റിക്വസ്റ്റ് #{id} രജിസ്റ്റർ ചെയ്തു.",
    jobCardStatusFound: "{regNo} സ്റ്റാറ്റസ്: ജോബ് കാർഡ് #{jobCard}, സ്റ്റേജ്: {stage}, സമയം: {estTime}.",
    serviceEstimateProvided: "{vehicle} ({serviceType}) ചെലവ് ഏകദേശം: {estimate}.",
    humanHandoff: "കസ്റ്റമർ കെയർ എക്സിക്യൂട്ടീവിലേക്ക് കണക്ട് ചെയ്യുന്നു, കാത്തിരിക്കുക.",
    couldNotUnderstand: "ക്ഷമിക്കണം, മനസ്സിലായില്ല. വീണ്ടും പറയാമോ?",
    farewell: `${AUTOMOBILE_BRAND_NAME}-ലേക്ക് വിളിച്ചതിന് നന്ദി. സുരക്ഷിതമായി യാത്ര ചെയ്യുക!`,
    alreadyConfirmed: "നിങ്ങളുടെ ബുക്കിംഗ് ഇതിനകം സ്ഥിരീകരിച്ചിട്ടുണ്ട് — റഫറൻസ് ഐഡി {id}.",
  },
  "kn-IN": {
    greeting: `ನಮಸ್ಕಾರ! ${AUTOMOBILE_BRAND_NAME} ಗೆ ಸ್ವಾಗತ. ಹೊಸ ಕಾರುಗಳು, ಟೆಸ್ಟ್ ಡ್ರೈವ್ ಮತ್ತು ಸರ್ವೀಸ್ ಬುಕಿಂಗ್‌ನಲ್ಲಿ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ. ಇಂದು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?`,
    askName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ತಿಳಿಸುವಿರಾ?",
    askMobile: "ಧನ್ಯವಾದಗಳು {name}! ನಿಮ್ಮ 10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ತಿಳಿಸಿ?",
    askVehicle: "ಯಾವ ಕಾರು ಮಾದರಿಯಲ್ಲಿ ಆಸಕ್ತಿ ಇದೆ — Creta, Nexon, Brezza, ಅಥವಾ EV?",
    askRegNumber: "ನಿಮ್ಮ ವಾಹನದ ನೋಂದಣಿ ಸಂಖ್ಯೆ (ಉದಾ: UP16AB1234) ತಿಳಿಸುವಿರಾ?",
    askServiceType: "ನಿಮ್ಮ {vehicle} ಗೆ ಯಾವ ರೀತಿಯ ಸರ್ವೀಸ್ ಬೇಕು — ಜನರಲ್ ಸರ್ವೀಸ್ ಅಥವಾ ರಿಪೇರಿ?",
    askDealer: "ಗುರಗಾಂವ್, ನೋಯ್ಡಾ, ಅಥವಾ ದಕ್ಷಿಣ ದೆಹಲಿ — ಯಾವ ಸೆಂಟರ್ ಅನುಕೂಲಕರ?",
    askSlot: "ಸೋಮವಾರದಿಂದ ಶನಿವಾರದವರೆಗೆ ಬೆಳಿಗ್ಗೆ 9:00 ರಿಂದ ಸಂಜೆ 6:30 ರವರೆಗೆ ತೆರೆದಿರುತ್ತದೆ. ಯಾವಾಗ ಬರಲು ಬಯಸುವಿರಿ?",
    askTime: "{date} ದಿನಾಂಕ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ. ಯಾವ ಸಮಯಕ್ಕೆ ಬರಲು ಬಯಸುವಿರಿ?",
    askPurchaseTimeline: "ಯಾವಾಗ ಕಾರು ಖರೀದಿಸಲು ಯೋಚಿಸುತ್ತಿದ್ದೀರಿ?",
    outOfHours: "ಕ್ಷಮಿಸಿ, ಭಾನುವಾರ ರಜೆ ಇರುತ್ತದೆ. ದಯವಿಟ್ಟು ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    serviceConfirmation: "ದೃಢೀಕರಿಸುತ್ತಿದ್ದೇನೆ: {name}, ಮೊಬೈಲ್ {mobile}, {vehicle} ({regNo}), {dealer} ಸೆಂಟರ್‌ನಲ್ಲಿ {slot} ರಂದು. ಇದು ಸರಿಯೇ?",
    testDriveConfirmation: "ದೃಢೀಕರಿಸುತ್ತಿದ್ದೇನೆ: {name}, {vehicle} ಟೆಸ್ಟ್ ಡ್ರೈವ್ {dealer} ನಲ್ಲಿ {slot} ರಂದು. ಬುಕ್ ಮಾಡಲೇ?",
    salesLeadConfirmation: "ಧನ್ಯವಾದಗಳು {name}! ನಮ್ಮ ಮಾರಾಟ ಪ್ರತಿನಿಧಿ ಶೀಘ್ರದಲ್ಲೇ {mobile} ನಲ್ಲಿ ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    bookingConfirmed: "ನಿಮ್ಮ ಬುಕಿಂಗ್ ದೃಢಪಟ್ಟಿದೆ! ರೆಫರೆನ್ಸ್ ಐಡಿ {id}. ವಿವರಗಳನ್ನು ವಾಟ್ಸಾಪ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
    roadsideAssistanceAlert: "ತುರ್ತು ರಸ್ತೆ ಬದಿಯ ಸಹಾಯಕ್ಕಾಗಿ 1800-102-9999 ಗೆ ಕರೆ ಮಾಡಿ. ರಿಕ್ವೆಸ್ಟ್ #{id} ದಾಖಲಾಗಿದೆ.",
    jobCardStatusFound: "{regNo} ಸ್ಥಿತಿ: ಜಾಬ್ ಕಾರ್ಡ್ #{jobCard}, ಪ್ರಸ್ತುತ ಹಂತ: {stage}, ಸಿದ್ಧವಾಗುವ ಸಮಯ: {estTime}.",
    serviceEstimateProvided: "{vehicle} ({serviceType}) ಅಂದಾಜು ವೆಚ್ಚ: {estimate}.",
    humanHandoff: "ಗ್ರಾಹಕ ಸೇವಾ ಅಧಿಕಾರಿಯೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತಿದ್ದೇನೆ, ದಯವಿಟ್ಟು ಕಾಯಿರಿ.",
    couldNotUnderstand: "ಕ್ಷಮಿಸಿ, ಅರ್ಥವಾಗಲಿಲ್ಲ. ಪುನಃ ಹೇಳುವಿರಾ?",
    farewell: `${AUTOMOBILE_BRAND_NAME} ಗೆ ಕರೆ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ಸುರಕ್ಷಿತವಾಗಿ ಚಾಲನೆ ಮಾಡಿ!`,
    alreadyConfirmed: "ನಿಮ್ಮ ಬುಕಿಂಗ್ ಈಗಾಗಲೇ ದೃಢಪಟ್ಟಿದೆ — ರೆಫರೆನ್ಸ್ ಐಡಿ {id}.",
  },
  "pa-IN": {
    greeting: `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ${AUTOMOBILE_BRAND_NAME} ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਨਵੀਂ ਕਾਰ, ਟੈਸਟ ਡਰਾਈਵ ਜਾਂ ਸਰਵਿਸ ਬੁਕਿੰਗ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ। ਅੱਜ ਮੈਂ ਕੀ ਮਦਦ ਕਰਾਂ?`,
    askName: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦੱਸੋ ਜੀ?",
    askMobile: "ਧੰਨਵਾਦ {name} ਜੀ! ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦੱਸੋ?",
    askVehicle: "ਤੁਸੀਂ ਕਿਹੜੀ ਕਾਰ ਵਿੱਚ ਦਿਲਚਸਪੀ ਰੱਖਦੇ ਹੋ — ਜਿਵੇਂ Creta, Nexon, Brezza, XUV700 ਜਾਂ ਕੋਈ EV?",
    askRegNumber: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਗੱਡੀ ਦਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ (ਜਿਵੇਂ UP16AB1234) ਦੱਸੋ ਜੀ?",
    askServiceType: "ਤੁਹਾਡੀ {vehicle} ਨੂੰ ਕਿਸ ਤਰ੍ਹਾਂ ਦੀ ਸਰਵਿਸ ਚਾਹੀਦੀ ਹੈ — ਰੈਗੂਲਰ ਸਰਵਿਸ ਜਾਂ ਕੋਈ ਖਰਾਬੀ?",
    askDealer: "ਗੁੜਗਾਓਂ, ਨੋਇਡਾ ਜਾਂ ਸਾਊਥ ਦਿੱਲੀ — ਕਿਹੜਾ ਸ਼ੋਰੂਮ ਤੁਹਾਡੇ ਲਈ ਸੁਵਿਧਾਜਨਕ ਰਹੇਗਾ?",
    askSlot: "ਸੋਮਵਾਰ ਤੋਂ ਸ਼ਨੀਵਾਰ ਸਵੇਰੇ 9:00 ਤੋਂ ਸ਼ਾਮ 6:30 ਵਜੇ ਤੱਕ ਖੁੱਲ੍ਹਾ ਰਹਿੰਦਾ ਹੈ। ਤੁਸੀਂ ਕਦੋਂ ਆਉਣਾ ਚਾਹੋਗੇ?",
    askTime: "{date} ਨੋਟ ਕਰ ਲਿਆ ਹੈ ਜੀ। ਤੁਸੀਂ ਕਿਸ ਸਮੇਂ ਆਉਣਾ ਚਾਹੋਗੇ?",
    askPurchaseTimeline: "ਗੱਡੀ ਕਦੋਂ ਤੱਕ ਖਰੀਦਣ ਦੀ ਯੋਜਨਾ ਹੈ ਜੀ?",
    outOfHours: "ਮਾਫ਼ ਕਰਨਾ ਜੀ, ਐਤਵਾਰ ਛੁੱਟੀ ਹੁੰਦੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਕੰਮ ਵਾਲੇ ਦਿਨਾਂ ਵਿੱਚੋਂ ਸਮਾਂ ਚੁਣੋ।",
    serviceConfirmation: "ਕਨਫ਼ਰਮ ਕਰ ਦੇਵਾਂ: {name}, ਮੋਬਾਈਲ {mobile}, {vehicle} ({regNo}), {dealer} 'ਤੇ {slot} ਨੂੰ। ਕੀ ਇਹ ਸਹੀ ਹੈ?",
    testDriveConfirmation: "ਕਨਫ਼ਰਮ ਕਰ ਦੇਵਾਂ: {name}, {vehicle} ਦੀ ਟੈਸਟ ਡਰਾਈਵ {dealer} 'ਤੇ {slot} ਨੂੰ। ਕੀ ਬੁੱਕ ਕਰ ਦੇਵਾਂ?",
    salesLeadConfirmation: "ਧੰਨਵਾਦ {name} ਜੀ! ਸਾਡੀ ਸੇਲਜ਼ ਟੀਮ ਤੁਹਾਡੇ ਨਾਲ {mobile} 'ਤੇ ਜਲਦੀ ਸੰਪਰਕ ਕਰੇਗੀ।",
    bookingConfirmed: "ਤੁਹਾਡੀ ਬੁਕਿੰਗ ਕਨਫ਼ਰਮ ਹੋ ਗਈ ਹੈ ਜੀ! ਰੈਫਰੈਂਸ ਆਈਡੀ ਹੈ {id}। ਵੇਰਵੇ ਵਟਸਐਪ 'ਤੇ ਭੇਜ ਦਿੱਤੇ ਗਏ ਹਨ।",
    roadsideAssistanceAlert: "ਐਮਰਜੈਂਸੀ ਰੋਡਸਾਈਡ ਮਦਦ ਲਈ 1800-102-9999 'ਤੇ ਕਾਲ ਕਰੋ ਜੀ। ਟਿਕਟ #{id} ਦਰਜ ਹੋ ਚੁੱਕੀ ਹੈ।",
    jobCardStatusFound: "{regNo} ਸਥਿਤੀ: ਜਾਬ ਕਾਰਡ #{jobCard}, ਮੌਜੂਦਾ ਸਟੇਜ: {stage}, ਤਿਆਰ ਹੋਣ ਦਾ ਸਮਾਂ: {estTime}।",
    serviceEstimateProvided: "{vehicle} ({serviceType}) ਦਾ ਅੰਦਾਜ਼ਨ ਖਰਚਾ: {estimate}।",
    humanHandoff: "ਮੈਂ ਤੁਹਾਡੀ ਕਾਲ ਕਸਟਮਰ ਕੇਅਰ ਐਗਜ਼ੀਕਿਊਟਿਵ ਨਾਲ ਜੋੜ ਰਿਹਾ ਹਾਂ, ਕਿਰਪਾ ਕਰਕੇ ਲਾਈਨ 'ਤੇ ਰਹੋ।",
    couldNotUnderstand: "ਮਾਫ਼ ਕਰਨਾ ਜੀ, ਸਮਝ ਨਹੀਂ ਆਇਆ। ਦੁਬਾਰਾ ਦੱਸੋਗੇ?",
    farewell: `${AUTOMOBILE_BRAND_NAME} ਨੂੰ ਚੁਣਨ ਲਈ ਧੰਨਵਾਦ। ਸੁਰੱਖਿਅਤ ਡਰਾਈਵ ਕਰੋ, ਤੁਹਾਡਾ ਦਿਨ ਸ਼ੁਭ ਰਹੇ!`,
    alreadyConfirmed: "ਤੁਹਾਡੀ ਬੁਕਿੰਗ ਪਹਿਲਾਂ ਹੀ ਕਨਫ਼ਰਮ ਹੋ ਚੁੱਕੀ ਹੈ — ਰੈਫਰੈਂਸ ਆਈਡੀ {id}।",
  },
  "gu-IN": {
    greeting: `નમસ્તે! ${AUTOMOBILE_BRAND_NAME} માં આપનું સ્વાગત છે. નવી કાર, ટેસ્ટ ડ્રાઈવ કે સર્વિસ બુકિંગમાં મદદ કરી શકું છું. આજે હું શી મદદ કરું?`,
    askName: "કૃપા કરીને આપનું પૂરું નામ જણાવશો?",
    askMobile: "આભાર {name} જી! આપનો 10 અંકનો મોબાઈલ નંબર જણાવશો?",
    askVehicle: "આપ કઈ કાર મોડેલમાં રસ ધરાવો છો — જેમ કે Creta, Nexon, Brezza, કે EV?",
    askRegNumber: "આપની ગાડીનો રજીસ્ટ્રેશન નંબર (દા.ત. UP16AB1234) જણાવશો?",
    askServiceType: "આપની {vehicle} ને કેવી સર્વિસની જરૂર છે — રેગ્યુલર સર્વિસ કે કોઈ રિપેરિંગ?",
    askDealer: "ગુડગાંવ, નોઈડા કે સાઉથ દિલ્હી — કયું સેન્ટર અનુકૂળ રહેશે?",
    askSlot: "સોમવારથી શનિવાર સવારે 9:00 થી સાંજે 6:30 સુધી ખુલ્લું રહે છે. ક્યારે આવવાનું પસંદ કરશો?",
    askTime: "{date} નોંધી લીધું છે. કયા સમયે આવવું અનુકૂળ રહેશે?",
    askPurchaseTimeline: "ક્યારે ગાડી ખરીદવાનું વિચારી રહ્યા છો?",
    outOfHours: "માફ કરશો, રવિવારે રજા હોય છે. કામકાજના દિવસોમાં સમય પસંદ કરો.",
    serviceConfirmation: "તો કન્ફર્મ કરું: {name}, મોબાઈલ {mobile}, {vehicle} ({regNo}), {dealer} સેન્ટર પર {slot} ના રોજ. શું આ બરાબર છે?",
    testDriveConfirmation: "કન્ફર્મ કરું: {name}, {vehicle} ની ટેસ્ટ ડ્રાઈવ {dealer} ખાતે {slot} ના રોજ. બુક કરી દઉં?",
    salesLeadConfirmation: "આભાર {name} જી! અમારા સેલ્સ એક્ઝિક્યુટિવ આપનો {mobile} પર સંપર્ક કરશે.",
    bookingConfirmed: "આપનું બુકિંગ કન્ફર્મ થઈ ગયું છે! રેફરન્સ આઈડી {id}. વિગતો વ્હોટ્સએપ પર મોકલી દેવાઈ છે.",
    roadsideAssistanceAlert: "રોડસાઈડ આસિસ્ટન્સ માટે 1800-102-9999 પર કૉલ કરો. ઈમરજન્સી વિનંતી #{id} નોંધાઈ છે.",
    jobCardStatusFound: "{regNo} સ્થિતિ: જોબ કાર્ડ #{jobCard}, હાલનો તબક્કો: {stage}, તૈયાર થવાનો સમય: {estTime}.",
    serviceEstimateProvided: "{vehicle} ({serviceType}) અંદાજિત ખર્ચ: {estimate}.",
    humanHandoff: "કસ્ટમર કેર એક્ઝિક્યુટિવ સાથે વાત કરાવી રહ્યો છું, લાઈન પર રહેશો.",
    couldNotUnderstand: "માફ કરશો, સમજાયું નહીં. ફરીથી કહેશો?",
    farewell: `${AUTOMOBILE_BRAND_NAME} ને પસંદ કરવા બદલ આભાર. સેફ ડ્રાઈવ કરો, આપનો દિવસ શુભ રહે!`,
    alreadyConfirmed: "આપનું બુકિંગ પહેલેથી જ કન્ફર્મ થયેલું છે — રેફરન્સ આઈડી {id}.",
  },
  "or-IN": {
    greeting: `ନମସ୍କାର! ${AUTOMOBILE_BRAND_NAME} କୁ ସ୍ୱାଗତ। ନୂଆ କାର୍, ଟେଷ୍ଟ ଡ୍ରାଇଭ୍ ବା ସର୍ଭିସ୍ ବୁକିଂରେ ସାହାଯ୍ୟ କରିପାରିବି। କିପରି ସାହାଯ୍ୟ କରିବି?`,
    askName: "ଆପଣଙ୍କର ପୂରା ନାମ କହିବେ କି?",
    askMobile: "ଧନ୍ୟବାଦ {name}! ଆପଣଙ୍କର 10 ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର କୁହନ୍ତୁ?",
    askVehicle: "ଆପଣ କେଉଁ କାର୍ ମଡେଲ୍ ପସନ୍ଦ କରୁଛନ୍ତି — Creta, Nexon, Brezza ବା EV?",
    askRegNumber: "ଆପଣଙ୍କ ଗାଡିର ପଞ୍ଜୀକରଣ ନମ୍ବର (ଯେପରିକି UP16AB1234) କହିବେ କି?",
    askServiceType: "{vehicle} ପାଇଁ କି ପ୍ରକାର ସର୍ଭିସିଂ ଦରକାର — ନିୟମିତ ସର୍ଭିସ୍ ନା କିଛି ମରାମତି?",
    askDealer: "ଗୁରଗାଓଁ, ନୋଇଡା ବା ଦକ୍ଷିଣ ଦିଲ୍ଲୀ — କେଉଁ ସେଣ୍ଟର ସୁବିଧାଜନକ ହେବ?",
    askSlot: "ସୋମବାରରୁ ଶନିବାର ସକାଳ 9:00 ରୁ ସନ୍ଧ୍ୟା 6:30 ପର୍ଯ୍ୟନ୍ତ ଖୋଲା ରହେ। କେବେ ଆସିବାକୁ ଚାହାଁନ୍ତି?",
    askTime: "{date} ତାରିଖ ନୋଟ୍ କଲି। କେଉଁ ସମୟରେ ଆସିବେ?",
    askPurchaseTimeline: "ଗାଡି କେବେ କିଣିବାକୁ ଚାହୁଁଛନ୍ତି?",
    outOfHours: "କ୍ଷମା କରିବେ, ରବିବାର ବନ୍ଦ ରହେ। କାର୍ଯ୍ୟ ଦିବସ ମଧ୍ୟରୁ ସମୟ ଚୟନ କରନ୍ତୁ।",
    serviceConfirmation: "ନିଶ୍ଚିତ କରୁଛି: {name}, ମୋବାଇଲ୍ {mobile}, {vehicle} ({regNo}), {dealer} ରେ {slot} ରେ। ଏହା ଠିକ୍ ଅଛି ତ?",
    testDriveConfirmation: "ନିଶ୍ଚିତ କରୁଛି: {name}, {vehicle} ଟେଷ୍ଟ ଡ୍ରାଇଭ୍ {dealer} ରେ {slot} ରେ। ବୁକ୍ କରିଦେବି କି?",
    salesLeadConfirmation: "ଧନ୍ୟବାଦ {name}! ଆମର ବିକ୍ରୟ ପ୍ରତିନିଧି {mobile} ରେ ଯୋଗାଯୋଗ କରିବେ।",
    bookingConfirmed: "ଆପଣଙ୍କର ବୁକିଂ ନିଶ୍ଚିତ ହୋଇଗଲା! ରେଫରେନ୍ସ ଆଇଡି {id}। ବିବରଣୀ ହ୍ୱାଟସ୍ଆପ୍‌ରେ ପଠାଯାଇଛି।",
    roadsideAssistanceAlert: "ରୋଡ୍‌ସାଇଡ୍ ସହାୟତା ପାଇଁ 1800-102-9999 ରେ କଲ୍ କରନ୍ତୁ। ଅନୁରୋଧ #{id} ଦାଖଲ ହୋଇଛି।",
    jobCardStatusFound: "{regNo} ସ୍ଥିତି: ଜବ୍ କାର୍ଡ #{jobCard}, ବର୍ତ୍ତମାନ ପର୍ଯ୍ୟାୟ: {stage}, ସମୟ: {estTime}।",
    serviceEstimateProvided: "{vehicle} ({serviceType}) ଆନୁମାନିକ ଖର୍ଚ୍ଚ: {estimate}।",
    humanHandoff: "ଆମର ଗ୍ରାହକ ସେବା ପ୍ରତିନିଧିଙ୍କ ସହିତ କଥା କରାଉଛି, ଲାଇନ୍‌ରେ ରୁହନ୍ତୁ।",
    couldNotUnderstand: "କ୍ଷମା କରିବେ, ମୁଁ ବୁଝିପାରିଲି ନାହିଁ। ପୁଣି କହିବେ କି?",
    farewell: `${AUTOMOBILE_BRAND_NAME} କୁ କଲ୍ କରିଥିବାରୁ ଧନ୍ୟବାଦ। ସୁରକ୍ଷିତ ଡ୍ରାଇଭ୍ କରନ୍ତୁ!`,
    alreadyConfirmed: "ଆପଣଙ୍କର ବୁକିଂ ପୂର୍ବରୁ ନିଶ୍ଚିତ ହୋଇସାରିଛି — ରେଫରେନ୍ସ ଆଇଡି {id}।",
  },
};

export function fillAutomobileTemplate(template: string, vars: Record<string, string>): string {
  let out = template;
  for (const [key, value] of Object.entries(vars)) {
    out = out.split(`{${key}}`).join(value);
  }
  return out;
}
